### ISSUE TITLE
links do not format when part of a bulleted list on main page, but do on direct link

### ISSUE THREAD

**Issue by toddgrotenhuis** [pimoore/microdotblog-hitchens#2] opened 2022-01-13 23:39 UTC
e.g. 
![image](https://user-images.githubusercontent.com/165077/149425827-d0eaa1ca-6c72-4639-98cc-a7fec95d7832.png)
vs.
![image](https://user-images.githubusercontent.com/165077/149425894-197b360e-bb20-4772-b32d-ce9738e16de3.png)
https://blog.grotenhuis.info/2022/01/10/recommendations-recap-recap.html

**Comment by pimoore** [comment] 2022-01-14 02:19
@toddgrotenhuis I’ve seen something similar in Tufte where it strips the post formatting on the index page.  Not surprising as I worked off that one as a base for Hitchens. :)  I’m going to have to look into this one deeper and will do some trials on my test blog.  This may take a bit longer to figure out, so I’m going to submit the conversation change right now.

**Comment by pimoore** [comment] 2022-01-14 05:05
@toddgrotenhuis I’ve found the issue and workaround.  [This thread on the Hugo Discourse](https://discourse.gohugo.io/t/summary-stripping-tags/20927/3) talks about the problem, which is caused by the .Summary function stripping out HTML if it’s auto-summarizing as opposed to manual through the use of a ```<!--more-->``` tag.  It worked on my test blog which was also exhibiting the same behaviour.  I’m going to look into another issue so I can keep the plugin updates to a minimum, but here’s the code in question if you want to change it yourself in the meantime.

In the layouts/partials/li.html file, change this:
```
{{ else if .Truncated }}
	<p>{{ .Summary }}</p>
```

To this:
```
{{ else if .Truncated }}
	<p>{{ .Content | safeHTML | truncate 200 }}</p>
```

This will preserve the formatting and html tags.

**Comment by pimoore** [comment] 2022-01-16 03:43
This is fixed and changed in the code, and will be included with the next update.

**Comment by toddgrotenhuis** [comment] 2022-01-21 02:17
Unfortunately there may be more to solve, here. Check out this post I just made. (Main page, then post)

![image](https://user-images.githubusercontent.com/165077/150453755-96d0d498-49d6-45fe-a2f6-8091d99c226a.png)
![image](https://user-images.githubusercontent.com/165077/150453773-1d9d19af-92c8-43db-8fcb-24554b66144b.png)
https://blog.grotenhuis.info/2022/01/20/im-familiar-with.html

(note: yes, I am on the latest)

**Comment by pimoore** [comment] 2022-01-21 02:28
What version of the plugin are you currently running, it should be 1.2.0?  I see you still have the horizontal rule line present above the Conversation section, which I removed as it seemed redundant since I added the text to delineate the section.

**Comment by pimoore** [comment] 2022-01-21 15:09
Seeing this on my test site as well when I tried it.  I’ll have to do some more digging.

**Comment by toddgrotenhuis** [comment] 2022-01-21 15:24
ok, where do i find version, btw? All i know to do is check on plugins page like this:

![image](https://user-images.githubusercontent.com/165077/150553132-86643943-4d17-4b16-8e06-f8b4a31d9ab0.png)

**Comment by pimoore** [comment] 2022-01-21 16:01
To find the version, you have to go into the custom themes under Design, and the plugin will actually be listed.  Once you click on it you can then open the plugin.json template to verify the version.  I’m going to ping Manton to see if we can change this to show a version right on the plugin screen instead.

As far as the post display issue, I figured out the problem as it was only happening with your posts that included a list.  My original version of the theme used a different format on the index page which more closely matched Pat’s original, but it had list styling disabled.  This was leftover in the CSS file and causing the ```<li>``` and ```<a>``` tags to be stripped.

This will be included in the next update, but if you want to fix it yourself in the interim, remove these 3 blocks from the CSS file:

```
.home li {
	list-style: none;
	text-decoration: none;
	background: none;
	padding: 1em 0;
}

.home li a {
	text-decoration: none;
}

.home li p {
	margin: 0;
}
```

**Closed as completed by pimoore** 2022-01-21 16:01 UTC
Labels: bug
